sudo: required
services:
- docker
language: node_js
node_js:
- '6'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: 1G/Q3Xmm9Q9l90r2Z4LvxxP8ka18mUGJU9tkr/ykFWZYZbcJlWrO8xJp37c0Dt6VpKbyLSgmFRlal3WBaFGZfZ1RqVlChts62qQO7b8RWZ7kMIXPl+RVShO7v2Yqb9JdI1+AOjDbOwGOvOhYnUQQ26Z6XwVcSLdXoyjDOyTLIVWtniBJJooDI57fxIGVuBbvBxgdvOTVJjfqSbQM/U8LMOJv74M4mYp053CqO9Qm3Yey/77OMLpR4eI0Jpby2ZbCp5VZztttWzBvkWnPWQLoxN2qRTcC7zILpfoB9wgmAK84PkAbvC+pQrLH3O/Ko/2XGqxMjQZe8iBe+bhkboNxctCDzF/VjJOQritjR0HqEBe7707n+s7Od3tX5riyt57gYbqALb2qHM4AQoLq9yCU7q3rYbgHw5IF1i5sxZBqQttyil748cF7nI3zGKFKa0uPNFrqSF7Sm3v4r+orX9FHKecI7vq2rsNmxSya/2mVyU0CCuHK973ZMqyG/DCQPd4mUeNJLyfgr0K8f4LntjgNo2oQLQ8qZhauxK0+kIoMn6uEA+dFRkF2k6GG8zT5d4axDIljYk+zauzjJxbPJZ3LDt0WdpoznwRUBHoRBBRu3hgmDKQ7GhM0HKOdyinIpUQEMWLHxi5BTVPf+V0efbxvQ3g/5YZGYBSj92Or78r1uEg=
  - secure: qyU45ba9ivKRmX3ajn2cOPXlHgHjC0xAQMSqk7k7Kg3DgWMo5PhmxuTbe0MPaUGAqbAqYHbKJ2zV65hPkWaZk4oXAEGcT9X1iHAqhQ18NWjDvNbE5e0oUcuw2PWjdiv2YA/0OysbNTYJhE/6yVdIErZhsTGFlN52StFukqXnYCQ+6eRY3QNytS/oLS848/LR2ItmfIP12Zr31p3k6amXJGlkylZvmtNkahPgyL5iJ9juY3WKxDAIaevuY7wd8J+9ODUWfgcrtSJpEzaJFtip6Z4IIiMnSSONveO1qa8RGwB2OW5yhGicuI0XnAbKuTnLd7faOe5kn6M56MMvsdzemeuJacZGZxP+MdyoJh5JBeblKfX6CVPAFr8yUCYoeGeRZq9DwzBJnNJbdf5buv376qUcSIhckjYPy7pwP1y9oljNzrX2NadPp1VbIp9eabZgY96EZJSgqmnuWBco3gz/feEi1EAbaUi/F9pEE46Q4GYUYo5lePr3CQNrckjZ9e5N2clIeoKHFpZPCZU22MP7h+BUxVP3FN1eqSSBEXOnWeohTVOxrtLC8xs93bUPwVmR+xoCBqcrjfIWpniAxQjgjYRIK9x9+HyrGyZW5BodOVts8pkQrJLP1x4EOMMMO5+QZHeWo2IKmAqWDI5WA0l4Nvr/zKcr6I9fop2d3RYuLMc=
  - secure: PvOY9upqqgOQ3gmh02cksO+E5BVW47GcHxz0tzgvGHrbynC5SpMYvXYJkJQGCG+XAORmXaigHeOrR/HcGs5pO2BNf3JpuRNJ/lTqIzeopoV4sGfIoE9z/XIu1IewzpY4A8HJO6p7EDxsOKXQon7r+s4eGk2w5gFffcJRNQuH2qs6Btig8LBdDFjrwO9AkURLjs+ms8fbd4nkLacUwVBXXNI/ecGxLpZPNEGOwPN1eSf4PUZnunlMxVjmx5gM2TMbNVbQ/b1wzuS9mOQ2b14WCD3XZHpKRjuN7MsrAI06cafeDD+wwF7uE2yC88e5BOekavbd8xGBWOSz13RYb1hF3P/9GI4BgsPRBLzaIdm+rX7MjwwLRLqTzYoP/9F5LA7r+BPpbdaGdXq7nmnbkHV2ab1wRKf6FwRRK5KDrqNSMVuSz2Nquuzrn90m/aRfeh8U9+pGCgBxNXRyv92Gu1XlyGXQMWvNFXbhQxFkVpF9JyqeVnUTOmVzvmhO85ado5Eo3mi8Eu/n6jppwM+GT0BrR7LNJXDPRMKBqj0dKSWSr8ma8VLkbKS0QhMGITqKtMHf/EZ59mNAjMSAkioIqSQd1Sjz/M1cymruPHNZ+YqydmZaa/v2IfIVQRc3AFbMs3r0T1u9sD9g4QwqZCTGphJDnFFeK6f1H9LNNh7AwN1ila8=
install:
- chmod +x buildTypescript.sh; ./buildTypescript.sh
script: true
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=qcifengineering/redbox-portal
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
