version: '3.1'
networks:
  main:
services:
  redboxportal:
    build: .
    image: qcifengineering/redbox-portal:latest
    ports:
       - "1500:1500"
    restart: always
    volumes:
       - ".:/opt/redbox-portal"
    expose:
       - "1500"
    environment:
      - NODE_ENV=development
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
    networks:
     main:
       aliases:
         - rbportal
    entrypoint: /bin/bash -c "cd /opt/redbox-portal && node app.js"
  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata"
      - "/mnt/data/mongo/data/db:/data/db"
      - "/var/log/mongo:/var/log/mongo"
    networks:
      main:
        aliases:
          - mongodb
    ports:
       - "27017:27017"
  redbox:
    image: qcifengineering/redbox:2.x
    expose:
       - "9000"
    environment:
      - RB_API_KEY=c8e844fc-8550-497f-b970-7900ec8741ca
      - RAID_URL=https://api.raid.org.au:8000/
      - RAID_KEY=
    volumes:
        - "/mnt/data/redbox:/opt/redbox/data"
        - "/var/log/redbox:/opt/redbox/home/logs"
    networks:
      main:
        aliases:
          - redbox
    ports:
       - "9000:9000"
