jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 12.16.0
      - docker/install-docker-tools
      - setup_remote_docker
      - run: npm install
      - run: node_modules/.bin/tsc
      - run: (cd angular && npm install)
      - run: (chmod +x dev_build/buildNgApps.sh && dev_build/buildNgApps.sh)
      - run: (chmod +x dockerhub_deploy.sh && ./dockerhub_deploy.sh)
orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - build