jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 12.16.0
      - run: npm install
      - run: node_modules/.bin/tsc
      - run: (cd angular && npm install)
      - run: (chmod +x dev_build/buildNgApps.sh && dev_build/buildNgApps.sh)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine: true
    steps:
      - docker/install-docker-compose
      - attach_workspace:
           at: /home/circleci/project
      - node/install:
          node-version: 12.16.0
      - run: node_modules/.bin/tsc -p tsconfig-codecov.json
      - run: docker build -t inttest .
      - run: (cd support/integration-testing && chmod +x triggerIntegrationTests.sh && ./triggerIntegrationTests.sh)
      #- run: nyc report --reporter=text-lcov > coverage.lcov;codecov -t $CODECOV_TOKEN; rm coverage.lcov
      - run: node_modules/.bin/tsc
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
            at: /home/circleci/project
      - docker/install-docker-compose
      - run: (chmod +x dockerhub_deploy.sh && ./dockerhub_deploy.sh)
  generate-docs:
    machine: true
    steps:
      - attach_workspace:
            at: /home/circleci/project
      - node/install:
          node-version: 12.16.0
      - docker/install-docker-compose
      - run: npm run doc-ng2
orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0
version: 2.1
workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - generate-docs:
          requires:
            - test