version: 2
orbs:
  node: circleci/node@4.0.0
jobs:
 build:
   machine: true
   steps:
     - checkout
     - node/install
     - npm install
     - node_modules/.bin/tsc
     - cd angular && npm install