jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 12.16.0
      - run: npm install
      - run: node_modules/.bin/tsc
      - run: (cd angular && npm install)
      - run: (chmod +x dev_build/buildNgApps.sh && dev_build/buildNgApps.sh)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine: true
    steps:
      - docker/install-docker-compose
      - attach_workspace:
           at: /home/circleci/project
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm install 12.16.0 && nvm use 12.16.0
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm use 12.16.0 && node_modules/.bin/tsc -p tsconfig-codecov.json
      - run: docker build -t inttest .
      - run: (cd support/integration-testing && chmod +x triggerIntegrationTests.sh && ./triggerIntegrationTests.sh)
      #- run: nyc report --reporter=text-lcov > coverage.lcov;codecov -t $CODECOV_TOKEN; rm coverage.lcov
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm use 12.16.0 && node_modules/.bin/tsc
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - setup_remote_docker
      - attach_workspace:
            at: /home/circleci/project
      - docker/install-docker-compose
      - run: (chmod +x dockerhub_deploy.sh && ./dockerhub_deploy.sh)
  generate-docs:
    machine: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - "50:0c:a1:7f:b6:64:84:42:01:61:0f:76:3f:e4:78:ff"
      - attach_workspace:
            at: /home/circleci/project
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm install 12.16.0 && nvm use 12.16.0
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm use 12.16.0 && npm run doc-ng2
      - run: export NVM_DIR=/opt/circleci/.nvm && source /opt/circleci/.nvm/nvm.sh && nvm use 12.16.0 && npm install -g --silent gh-pages@2.0.1 && git config user.email "ci-build@redboxresearchdata.com.au" && git config user.name "ci-build" && gh-pages --dotfiles --message "Updating documents? --dist support/docs/generated/ng2`
orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0
version: 2.1
workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - generate-docs:
          requires:
            - test